In [1]:
#machine learning 3
#1 supervised 
#2 unsupervised
#3 reinforcement 

In [2]:
#supervised learning 
#dataset already available 
#classification -> cat or dog
#regression-> llm dataset ->

In [3]:
#unsupervised learning 
# dataset unlabeled 
#clustring  ->feature color red labeled  
#assocation ->based on the similar features it adds the object/data in it's group 
#dimensionality reduction 
#outlier detection 


In [4]:
#Numpy 
l1=[1,2,3,4,5]
print(l1)
type(l1)

[1, 2, 3, 4, 5]


list

In [3]:
#numpy -> coded in c language 10X faster than the regular list 
#importing numpy
import numpy as np #np shorter name 

In [4]:
array=np.array([1,2,3,4,5])
print(array)
type(array)

[1 2 3 4 5]


numpy.ndarray

In [7]:
#why to use numpy array over the list
#1-> matrix operations
#2-> vector operations  
#3-> speed

In [9]:
#vectors 
#dot product 
#cross product 
#projection 
a=np.array([1,2,3])
b=np.array([4,5,6])
a_dot_b=np.dot(a,b)
print(a_dot_b)

[-3  6 -3]


In [ ]:
#1*4+2*5+3*6

In [11]:
#how to find the dimension or the shape of the numpy array 
array=np.array([1,2,3,4,5])
print(array)
array.shape

[1 2 3 4 5]


(5,)

In [48]:
#2D array
b=np.array([(1,2,3,4,5),(6,7,8,9,10),(5,1,2,3,9)])
print(b)
type(b)
b.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 5  1  2  3  9]]


(3, 5)

In [30]:
#conversion of numpy arrays from int to float values 
b=np.array([(1,2,3,4,5),(6,7,8,9,10)],dtype=float)#->dtype is used to define or convert the datatype from one to another 
print(b)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [36]:
#intial placeholder in numpy array
#lets create the numpyarrays with all the values 0
x=np.zeros((3,3)) #-> zeros is the numpy function which declares the whole matrix to zero 
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [37]:
#for one
y=np.ones((3,4))
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [42]:
#defining the values for any random number 
z=np.full((3,4),5) #syntax np.full((no of rows,no of columns),the element)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [43]:
#identity matrix (p==q) agar pXq
identity_matrix=np.eye((3))
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [44]:
#creating the arrays with random values 
A=np.random.random((4,5))
print(A)

[[0.23123952 0.40662778 0.53497461 0.95126771 0.58288009]
 [0.07206969 0.85000016 0.16351106 0.92602681 0.50174452]
 [0.91759725 0.38886297 0.13433406 0.46085264 0.33978633]
 [0.11406315 0.10333309 0.91725786 0.40109984 0.68188138]]


In [45]:
#when you use random.random the values of the arrays will lie between 0 and 1

In [46]:
b=np.random.randint(10,1000,(4,4))
print(b)

[[397 116 862 701]
 [324 489 235 405]
 [ 62 314 412 476]
 [652 468 834 387]]


In [ ]:
#syntax np.random.randint(starting range,ending range,(dim))

In [1]:
#My Practice
import numpy as np

In [4]:
List_1 = np.array([4,7,8,1])
print(List_1)

[4 7 8 1]


In [5]:
List_2 = np.array([(3,1,6,7) , (1,9,2,5) ])
print(List_2)

[[3 1 6 7]
 [1 9 2 5]]


In [7]:
List_3 = np.zeros((3,3))
print(List_3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
List_4 = np.ones((4,3))
print(List_4)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
List_4 = np.full((2,3) , 2)
print(List_4)

[[2 2 2]
 [2 2 2]]


In [11]:
List = np.random.random((2,4))
print(List)

[[0.81003473 0.46183849 0.75033995 0.1207623 ]
 [0.81017315 0.18123102 0.83757095 0.40894908]]


In [13]:
List = np.random.randint(2,10,(3,3))
print(List)

[[5 4 7]
 [6 4 9]
 [5 4 4]]


In [15]:
id_matrix = np.eye((4))
print(id_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
List = np.array([(1,2,3),(4,5,6)],dtype = float)
print(List)

[[1. 2. 3.]
 [4. 5. 6.]]


In [19]:
List.shape

(2, 3)