In [2]:
#Numpy full covered
import numpy as np

In [3]:
#List vs numpy time taken
from time import process_time 

In [9]:
#time taken by the numpy arrays
np_array=np.array([i for i in range(100000000)])
start_time=process_time()
np_array += 5
end_time=process_time()
print(end_time-start_time)

0.125


In [10]:
#list
list1=[1,2,3,4]
print(list1)
type(list1)

[1, 2, 3, 4]


list

In [17]:
#how to create the numpy array
array=np.array([1,2,3,4,5])
print(array)
type(array)


[1 2 3 4 5]


numpy.ndarray

In [3]:
#let's create the 1-d arrays
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [25]:
#shows the rows and columns of array
a.shape

(5,)

In [26]:
# 2-d arraays 
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [27]:
#number of rows and column of the 2-d arrays
b.shape

(2, 4)

In [7]:
#now we will convert the normal int arrays to floating arrays 
c=np.array([(1,2,3,4),(5,6,7,8),],dtype=float) #default value is integer if you do not mention 
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [4]:
#inital placeholder in numpy array
#lets create the array of zeros the syntax is np.zeros((no of rows,number of columns))
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
#now for ones 
y=np.ones((4,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
#lets create the arrays for any specific values 
#syntax will be np.full((number of rows,number of columns),the element)
z=np.full((4,5),5)
print(z)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [14]:
#creating the diagonal matrix all the diagonal elements are 1
#syntax is np.eye(no of rows and columns cuz identity can only exists in square matrix p==q)
e=np.eye((4))
print(e)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
#creating the arrays with random values
A=np.random.random((3,4))
print(A)

[[0.23055505 0.37039293 0.02551679 0.70183331]
 [0.71720355 0.00880913 0.60802182 0.40616233]
 [0.21308748 0.54694665 0.00789762 0.96667279]]


In [19]:
# remember the values will be in between 0 and 1

In [24]:
#now creatting the arrays with integar values 
#syntax np.random.randint(starting range,ending range(rows,columns))
B=np.random.randint(10,1000,(5,4))
print(b)

[[608 323 932  34]
 [899 382 401 417]
 [431 452 121 296]
 [617  95 934 559]
 [278 218 747 598]]


In [29]:
#creating the array with evenly spaced values
even=np.linspace(10,50,6)# --> the 6 specifies the number of values that are need to be printed
print(even)

[10. 18. 26. 34. 42. 50.]


In [30]:
#creating the array with evenly sapced values but without how many values should be printed 
#syntax np.arange(start range,end range,step) step refers to how many gaps between the numbers should be taken
even1=np.arange(10,60,5)
print(even1)

[10 15 20 25 30 35 40 45 50 55]


In [32]:
#convert the list to a numpy arrays
list1=[1,2,3,4,5]
nd_array1=np.asarray(list1)
print(nd_array1)
type(nd_array1)

[1 2 3 4 5]


numpy.ndarray

In [33]:
#Analyzing the numpy arrays
nd=np.random.randint(10,1000,(8,8))
print(nd)

[[ 88 235 642 110 690 807 575 209]
 [ 45 677 782 740 432 335 991 593]
 [262 721  16 113  61 159 303 127]
 [424 775 874  55 291  48 145 681]
 [583 335 938 459 239 814 426  61]
 [336 593 143 314  12 586 201 600]
 [815 529 462 764 740 124 484 104]
 [873 327  46 828 219  56 288 516]]


In [34]:
#shape
nd.shape

(8, 8)

In [35]:
#printing the dimension of the array
nd.ndim #it shows the dimesions 2d in this case

2

In [36]:
#total number of elements
nd.size

64

In [37]:
#checking the datatypes of the arrays
nd.dtype

dtype('int32')

In [38]:
#mathematical operations performed on the arrays

In [1]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
final_list=list1+list2 #the "+" here only concatinates/joins the two lists 
print(final_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [4]:
a=np.random.randint(10,20,(3,3))
b=np.random.randint(20,30,(3,3))

In [5]:
print(a)
print(b)
print(a-b)
print(a+b)
print(a*b)

[[19 10 12]
 [16 15 15]
 [12 16 16]]
[[27 29 29]
 [25 24 25]
 [28 20 26]]
[[ -8 -19 -17]
 [ -9  -9 -10]
 [-16  -4 -10]]
[[46 39 41]
 [41 39 40]
 [40 36 42]]
[[513 290 348]
 [400 360 375]
 [336 320 416]]


In [4]:
#using functions suppose we have to add then
a=np.random.randint(10,20,(3,3))
b=np.random.randint(20,30,(3,3))
print(a)
print(b)

[[18 17 18]
 [10 14 15]
 [19 14 16]]
[[23 27 25]
 [23 29 23]
 [23 25 20]]


In [6]:
#another method of doing that above
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[41 44 43]
 [33 43 38]
 [42 39 36]]
[[ -5 -10  -7]
 [-13 -15  -8]
 [ -4 -11  -4]]
[[414 459 450]
 [230 406 345]
 [437 350 320]]
[[0.7826087  0.62962963 0.72      ]
 [0.43478261 0.48275862 0.65217391]
 [0.82608696 0.56       0.8       ]]


In [7]:
#Arryas manupulation 

In [8]:
arr=np.random.randint(10,20,(2,3))
print(arr)
arr.shape


[[19 10 12]
 [16 12 10]]


(2, 3)

In [11]:
#now let's do the transpose of the matrix
trans=np.transpose(arr)
print(trans)
trans.shape

[[19 16]
 [10 12]
 [12 10]]


(3, 2)

In [13]:
#using short form
trans2=arr.T
print(trans2)
trans2.shape

[[19 16]
 [10 12]
 [12 10]]


(3, 2)

In [14]:
#now reshaping the array
newarr=np.random.randint(0,10,(3,4))
print(newarr)
newarr.shape

[[6 1 3 0]
 [3 7 1 6]
 [6 1 9 0]]


(3, 4)

In [17]:
Reshape=newarr.reshape(4,3)
print(Reshape)
Reshape.shape

[[6 1 3]
 [0 3 7]
 [1 6 6]
 [1 9 0]]


(4, 3)