In [3]:
#importing the numpy array
import numpy as np 

In [5]:
#matirx addition 
#the matrix can only be added when there shape is same there dimension should always be same 
#lets take the random integer matrix 
a=np.random.randint(10,20,(3,3))
b=np.random.randint(30,40,(3,3))
print("first matrix is")
print(a)
print("the second matrix is")
print(b)


first matrix is
[[18 14 16]
 [11 14 14]
 [11 13 10]]
the second matrix is
[[30 38 32]
 [35 37 37]
 [32 31 37]]


In [13]:
#lets perform the matrix addtion 
print("using function")
print(np.add(a,b))
print("manually without function")
print(a+b)

using function
[[48 52 48]
 [46 51 51]
 [43 44 47]]
manually without function
[[48 52 48]
 [46 51 51]
 [43 44 47]]


In [16]:
#lets perfrom the matrix subtraction
print("using function")
print(np.subtract(a,b))
print("manually without function")
print(a-b)

using function
[[-12 -24 -16]
 [-24 -23 -23]
 [-21 -18 -27]]
manually without function
[[-12 -24 -16]
 [-24 -23 -23]
 [-21 -18 -27]]


In [17]:
#matrix with scaler multiplication
print(5*a)

[[90 70 80]
 [55 70 70]
 [55 65 50]]


In [20]:
#matrix multiplication
print("using funciton")
print(np.multiply(a,b))
print("manually without function")
print(a*b)

using funciton
[[540 532 512]
 [385 518 518]
 [352 403 370]]
manually without function
[[540 532 512]
 [385 518 518]
 [352 403 370]]


In [21]:
#remember the method which is done by using function is faster than manual method 

In [1]:
#My Practice

In [2]:
import numpy as np

In [3]:
matrix_1 = np.random.randint(9,19,(2,3))
print("Matrix 1 :")
print(matrix_1)
matrix_2 = np.random.randint(7,21,(2,3))
print("Matrix 2 :")
print(matrix_2)

Matrix 1 :
[[10 15 10]
 [18 12  9]]
Matrix 2 :
[[14 17 16]
 [11 15 11]]


In [5]:
print("Using Function :")
print(np.add(matrix_1 , matrix_2))
print("Manual :")
print(matrix_1 + matrix_2)

Using Function :
[[24 32 26]
 [29 27 20]]
Manual :
[[24 32 26]
 [29 27 20]]


In [7]:
print("Using Function :")
print(np.multiply(matrix_1 , matrix_2))
print("Manual :")
print(matrix_1 * matrix_2)

Using Function :
[[140 255 160]
 [198 180  99]]
Manual :
[[140 255 160]
 [198 180  99]]


In [8]:
print("Using Function :")
print(np.subtract(matrix_1 , matrix_2))
print("Manual :")
print(matrix_1 - matrix_2)

Using Function :
[[-4 -2 -6]
 [ 7 -3 -2]]
Manual :
[[-4 -2 -6]
 [ 7 -3 -2]]


In [9]:
print("Using Function :")
print(np.divide(matrix_1 , matrix_2))
print("Manual :")
print(matrix_1 / matrix_2)

Using Function :
[[0.71428571 0.88235294 0.625     ]
 [1.63636364 0.8        0.81818182]]
Manual :
[[0.71428571 0.88235294 0.625     ]
 [1.63636364 0.8        0.81818182]]


In [15]:
print("Scalor Multiplication :")
division = np.divide(matrix_1,matrix_2)
print(10*division)

Scalor Multiplication :
[[ 7.14285714  8.82352941  6.25      ]
 [16.36363636  8.          8.18181818]]
