In [2]:
#importing the numpy library
import numpy as np #numpy simply means numerical python 

In [4]:
#creating the matrix using the numpy_array
matrix_1=np.array([[2,3],[3,4]])
print(matrix_1)

[[2 3]
 [3 4]]


In [6]:
matrix_1.shape

(2, 2)

In [7]:
#3X3 martrix can be also defined 
matrix2=np.array([[20,40,50],[60,70,80],[10,60,56]])
print(matrix2)

[[20 40 50]
 [60 70 80]
 [10 60 56]]


In [8]:
matrix2.shape

(3, 3)

In [10]:
#creating the matrices with random values
mat=np.random.rand(3,3)
print(mat)

[[0.61134229 0.69740163 0.02504796]
 [0.62832669 0.04816104 0.09254406]
 [0.27165923 0.55615745 0.72828089]]


In [11]:
#the values are between 0 and 1

In [12]:
mat2=np.random.randint(10,1000,(3,3))
print(mat2)

[[383 212 249]
 [780  71 332]
 [ 92 784 941]]


In [16]:
#matrix with all the values 1
mat=np.ones((3,3))
print(mat)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
#the values are in float let's change it to integer
mat=np.ones((3,3),dtype=int)
print(mat)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [18]:
#all the values with zero
mat=np.zeros((3,3))
print(mat)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
#now convert the values from float to int 
mat=np.zeros((3,3),dtype=int)
print(mat)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [21]:
#let's create the identity matrix
identity=np.eye(3,3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
#let's now find the transpose of the matrix
#lets take the random matrix
a=np.random.randint(10,100,(4,4))
print(a)

[[57 11 45 89]
 [18 58 58 45]
 [57 18 52 12]
 [27 94 41 21]]


In [25]:
transpose=np.transpose(a)
print(transpose )

[[57 18 57 27]
 [11 58 18 94]
 [45 58 52 41]
 [89 45 12 21]]


In [1]:
#My practice

In [2]:
import numpy as np

In [3]:
mat_1 = np.array([[1,2,3],[4,5,6]])
print(mat_1)         

[[1 2 3]
 [4 5 6]]


In [5]:
np.shape(mat_1)

(2, 3)

In [6]:
np.random.rand(4,5)

array([[0.2507797 , 0.67435733, 0.74947365, 0.82634946, 0.40240919],
       [0.88918162, 0.89668318, 0.41044001, 0.79830103, 0.18774191],
       [0.17209989, 0.30707417, 0.72291003, 0.37828324, 0.47214028],
       [0.3871125 , 0.62203736, 0.69969063, 0.81197362, 0.5381659 ]])

In [7]:
mat = np.random.randint(30,50,(4,3))
print(mat)

[[36 39 44]
 [43 37 30]
 [35 37 36]
 [30 41 33]]


In [8]:
print(mat.shape)

(4, 3)


In [11]:
id_mat = np.zeros((5,5))
print(id_mat)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
id_mat = np.ones((5,5))
print(id_mat)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
id_mat = np.eye(4)
print(id_mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
print(mat)
trp = np.transpose(mat)
print(trp)

[[36 39 44]
 [43 37 30]
 [35 37 36]
 [30 41 33]]
[[36 43 35 30]
 [39 37 37 41]
 [44 30 36 33]]
